export  const SCREEN_WIDTH = 800;
export  const SCREEN_HEIGHT = 600;

export  const PADDLE_WIDTH_PERCENTAGE = 0.5
export  const PADDLE_WIDTH = PADDLE_WIDTH_PERCENTAGE * SCREEN_WIDTH / 100
export  const PADDLE_HEIGHT_PERCENTAGE = 13
export  const PADDLE_HEIGHT = PADDLE_HEIGHT_PERCENTAGE * SCREEN_HEIGHT / 100

export  const PADDLE_SPEED = 5 / 10;
export  const BALL_SPEED = 3.5 /10;

export  const BALL_RADIUS_PERCENTAGE = 0.7
export  const BALL_RADIUS = BALL_RADIUS_PERCENTAGE * SCREEN_WIDTH / 100
export  const ANGLES_INTERVALS = [[120, 240], [300, 420]];

export  const WINNING_SCORE_PONTUATION = 7