SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

PADDLE_WIDTH_PERCENTAGE = 0.5
PADDLE_WIDTH = PADDLE_WIDTH_PERCENTAGE * SCREEN_WIDTH / 100
PADDLE_HEIGHT_PERCENTAGE = 13
PADDLE_HEIGHT = PADDLE_HEIGHT_PERCENTAGE * SCREEN_HEIGHT / 100
# pixel / ms
PADDLE_SPEED = 5 / 10

# pixel / ms
BALL_SPEED = 3.5 / 10

BALL_RADIUS_PERCENTAGE = 0.7
BALL_RADIUS = BALL_RADIUS_PERCENTAGE * SCREEN_WIDTH / 100
ANGLES_INTERVALS = [(120, 240), (300, 420)]

# Winning Pontuation
WINNING_SCORE_PONTUATION = 1
